/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.BufferedReader;
import java.io.PrintWriter;
import java.net.Socket;

/**
 *
 * @author m_hus
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        this.serverName = "localhost";
        this.PORT = 12345;
        this.name = "nickname";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextFilDiscuSP = new javax.swing.JScrollPane();
        jtextFilDiscu = new javax.swing.JTextPane();
        jtextListUsersSP = new javax.swing.JScrollPane();
        jtextListUsers = new javax.swing.JTextPane();
        jtextInputChat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");
        setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jtextFilDiscuSP.setViewportView(jtextFilDiscu);

        getContentPane().add(jtextFilDiscuSP);
        jtextFilDiscuSP.setBounds(10, 10, 260, 230);

        jtextListUsersSP.setViewportView(jtextListUsers);

        getContentPane().add(jtextListUsersSP);
        jtextListUsersSP.setBounds(290, 10, 100, 230);

        jtextInputChat.setText("jTextField1");
        getContentPane().add(jtextInputChat);
        jtextInputChat.setBounds(20, 270, 61, 20);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 260, 75, 23);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 240, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    private BufferedReader input;
    private PrintWriter output;
    private Socket server;
    private String oldMsg = "";
    private Thread read;
    private String serverName;
    private int PORT;
    private String name;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextPane jtextFilDiscu;
    private javax.swing.JScrollPane jtextFilDiscuSP;
    private javax.swing.JTextField jtextInputChat;
    private javax.swing.JTextPane jtextListUsers;
    private javax.swing.JScrollPane jtextListUsersSP;
    // End of variables declaration//GEN-END:variables
}
